entity: UnitsOfMeasure
key: UnitID
records:
- UnitID: BOTTLE
  Description: Bottle
  L3Code: EA
- UnitID: BOX
  Description: Box
  L3Code: EA
- UnitID: CAN
  Description: Can
  L3Code: EA
- UnitID: EA
  Description: Each
  L3Code: EA
- UnitID: HOUR
  Description: Hour
  L3Code: HUR
- UnitID: KG
  Description: Kg
  L3Code: KGM
- UnitID: LITER
  Description: Liter
  L3Code: LTR
- UnitID: METER
  Description: Meter
  L3Code: MTR
- UnitID: MINUTE
  Description: Minute
  L3Code: MIN
- UnitID: PACK
  Description: Pack
  L3Code: NMP
- UnitID: PALLET
  Description: Pallet
  L3Code: EA
- UnitID: PIECE
  Description: Piece
  L3Code: PCB
