entity: NumberingSequence
key: NumberingID
endpoint: bootstrap
records:
- NumberingID: APBILL
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: APPAYMENT
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: ARINVOICE
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: ARPAYMENT
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: BATCH
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: INADJUST
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: INISSUE
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: INKITASSY
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: INRECEIPT
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: POORDER
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: PORECEIPT
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: SOORDER
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
- NumberingID: SOSHIPMENT
  StartNbr: '000000'
  EndNbr: '999999'
  WarnNbr: '999990'
  NbrStep: 1
  StartDate: '1900-01-01'
