entity: ReasonCode
key: ReasonCodeID
endpoint: bootstrap
records:
- ReasonCodeID: INADJUST
  AccountID: '50300'
  Descr: Inventory adjustment
  SubID: '000000'
  Usage: Adjustment
- ReasonCodeID: INASSEMBLY
  AccountID: '50300'
  Descr: Kit assembly
  SubID: '000000'
  Usage: Assembly/Disassembly
- ReasonCodeID: INISSUE
  AccountID: '50300'
  Descr: Inventory issue
  SubID: '000000'
  Usage: Issue
- ReasonCodeID: INPI
  AccountID: '50300'
  Descr: Physical inventory variance
  SubID: '000000'
  Usage: Adjustment
- ReasonCodeID: INRECEIPT
  AccountID: '50300'
  Descr: Inventory receipt
  SubID: '000000'
  Usage: Receipt
- ReasonCodeID: PORETURN
  AccountID: '50300'
  Descr: Vendor return
  SubID: '000000'
  Usage: Vendor Return
