entity: INPreferences
key: HoldEntry
endpoint: bootstrap
records:
- HoldEntry: false
  AdjustmentReasonCode: INADJUST
  INProgressAcctID: '12300'
  INProgressSubID: '000000'
  INTransitAcctID: '12400'
  INTransitSubID: '000000'
  IssuesReasonCode: INISSUE
  PIReasonCode: INPI
  ReceiptReasonCode: INRECEIPT
  TransitBranchID: LAB5
  UpdateGL: true
