entity: PostingClass
key: PostClassID
endpoint: bootstrap
records:
- PostClassID: KITS
  COGSAcctID: '50000'
  COGSSubID: '000000'
  Descr: Assembled gateway kits
  InvtAcctID: '12200'
  InvtSubID: '000000'
  LCVarianceAcctID: '50200'
  LCVarianceSubID: '000000'
  POAccrualAcctID: '20200'
  POAccrualSubID: '000000'
  PPVAcctID: '50100'
  PPVSubID: '000000'
  SalesAcctID: '40000'
  SalesSubID: '000000'
- PostClassID: PARTS
  COGSAcctID: '50000'
  COGSSubID: '000000'
  Descr: Purchased components
  InvtAcctID: '12100'
  InvtSubID: '000000'
  LCVarianceAcctID: '50200'
  LCVarianceSubID: '000000'
  POAccrualAcctID: '20200'
  POAccrualSubID: '000000'
  PPVAcctID: '50100'
  PPVSubID: '000000'
  SalesAcctID: '40000'
  SalesSubID: '000000'
