entity: Warehouse
key: WarehouseID
endpoint: default
detail_keys:
  Locations: LocationID
records:
- WarehouseID: WH01
  Locations:
  - Active: true
    AssemblyAllowed: true
    Description: Main storage
    LocationID: MAIN
    PickPriority: 1
    ReceiptsAllowed: true
    SalesAllowed: true
    TransfersAllowed: true
  RMALocationID: MAIN
  ReceivingLocationID: MAIN
  ShippingLocationID: MAIN
