entity: POPreferences
key: HoldReceipts
endpoint: bootstrap
records:
- HoldReceipts: false
  RCReturnReasonCodeID: PORETURN
  AutoReleaseIN: true
  RegularPONumberingID: POORDER
  ReceiptNumberingID: PORECEIPT
  AutoReleaseAP: false
