entity: OrderType
key: OrderType
endpoint: bootstrap
records:
- OrderType: BL
  Active: false
- OrderType: CM
  Active: false
- OrderType: CR
  Active: false
- OrderType: CS
  Active: false
- OrderType: IN
  Active: false
- OrderType: MO
  Active: false
- OrderType: QT
  Active: false
- OrderType: RC
  Active: false
- OrderType: RM
  Active: false
- OrderType: RR
  Active: false
- OrderType: SA
  Active: false
- OrderType: SO
  Active: true
  FreightAcctID: '40100'
  FreightSubID: '000000'
- OrderType: TR
  Active: false
