entity: APPreferences
key: HoldEntry
endpoint: bootstrap
records:
- HoldEntry: false
  BatchNumberingID: BATCH
  InvoiceNumberingID: APBILL
  CheckNumberingID: APPAYMENT
  AutoPost: true
  RequireControlTotal: true
  RequireVendorRef: true
  RequireApprovePayments: true
