entity: CAPreferences
key: TransitAcctId
endpoint: bootstrap
records:
- TransitAcctId: '10200'
  TransitSubID: '000000'
  HoldEntry: false
  BatchNumberingID: BATCH
  AutoPostOption: true
  ReleaseAP: true
  ReleaseAR: true
