entity: StatementCycle
key: StatementCycleId
endpoint: bootstrap
records:
- StatementCycleId: MONTHLY
  AgeDays00: 30
  AgeDays01: 60
  AgeDays02: 90
  Day00: 1
  Descr: Monthly statements
  PrepareOn: Fixed Day of Month
