entity: CustomerClass
key: ClassID
records:
- ClassID: B2B
  ARAccount: '11000'
  ARSubaccount: '000000'
  CashDiscountAccount: '49000'
  CashDiscountSubaccount: '000000'
  CurrencyID: USD
  Description: B2B customers
  SalesAccount: '40000'
  SalesSubaccount: '000000'
  StatementCycleID: MONTHLY
  Terms: NET30
