entity: StockItem
key: InventoryID
records:
- InventoryID: ANT-LORA
  DefaultWarehouseID: WH01
  Description: LoRa antenna
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: ANT-LTE
  DefaultWarehouseID: WH01
  Description: LTE antenna
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: CBL-PWR
  DefaultWarehouseID: WH01
  Description: Power cable
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: ENCL-DIN
  DefaultWarehouseID: WH01
  Description: DIN-rail enclosure
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: ENCL-STD
  DefaultWarehouseID: WH01
  Description: Standard enclosure
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: MB-CM4
  DefaultWarehouseID: WH01
  Description: Gateway mainboard
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: MOD-LTE
  DefaultWarehouseID: WH01
  Description: LTE modem module
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: PSU-12V
  DefaultWarehouseID: WH01
  Description: 12V power supply
  ItemClass: PARTS
  ItemStatus: Active
- InventoryID: SD-32GB
  DefaultWarehouseID: WH01
  Description: 32GB industrial SD card
  ItemClass: PARTS
  ItemStatus: Active
