entity: KitSpecification
key:
- KitInventoryID
- RevisionID
detail_keys:
  StockComponents: StockInventoryID
records:
- KitInventoryID: GW-CELL
  RevisionID: V1
  Active: true
  Description: Cellular IoT Gateway bill of components
  StockComponents:
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ENCL-STD
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: MB-CM4
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: MOD-LTE
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ANT-LTE
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ANT-LORA
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: PSU-12V
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: SD-32GB
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: CBL-PWR
    UOM: EA
- KitInventoryID: GW-EDGE
  RevisionID: V1
  Active: true
  Description: Edge IoT Gateway bill of components
  StockComponents:
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ENCL-STD
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: MB-CM4
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ANT-LORA
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: PSU-12V
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: SD-32GB
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: CBL-PWR
    UOM: EA
- KitInventoryID: GW-RAIL
  RevisionID: V1
  Active: true
  Description: DIN-Rail Industrial Gateway bill of components
  StockComponents:
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ENCL-DIN
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: MB-CM4
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: ANT-LORA
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: PSU-12V
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: SD-32GB
    UOM: EA
  - AllowComponentQtyVariance: false
    ComponentQty: 1.0
    StockInventoryID: CBL-PWR
    UOM: EA
