action: ProcessAll
entity: ManagePeriods
endpoint: bootstrap
record:
  Action: Open
  FromYear: '2026'
  ToYear: '2026'
  OrganizationID: LAB5
done_when:
  entity: CompanyPeriod
  filter: FinancialYear eq '2026' and Status eq 'Open'
